# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  - name: rgname
    value: 'rg-fs-coe-containerapps'  
  - name: ServiceConnectionName
    value: 'containerapp-sp-dev'
  - name: wapp-name
    value: 'containterapp-codegenerator-dev-eus'
  - name: BuildConfiguration
    value: 'Release'
  - name: location
    value: 'eastus'
  
stages:
  - stage: Stage_BuildAPI
    displayName: 'Build API'
    jobs:
    - job: Job_BuildAPI
      displayName: 'API - Build Job'
      pool:
       vmImage: ubuntu-latest
      steps:      
      - task: DotNetCoreCLI@2
        displayName: 'Restore_API'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build_API'
        inputs:
          command: 'build'
          projects: '**/APIMDevOpsCodeGenerator.Web.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'Publish_API'
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/Release-API'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Release-API'
          ArtifactName: 'drop'
          publishLocation: 'Container'

  - stage: Stage_DeployAPI
    displayName: 'Deploy Code Generator'
    jobs:
    - job: Job_DeployAPI
      displayName: 'App Service - Code Generator Job'
      pool:
       vmImage: ubuntu-latest
      steps:
       - task: DownloadBuildArtifacts@0
         inputs:
           buildType: 'current'
           downloadType: 'single'
           artifactName: 'drop'
           downloadPath: '$(Build.ArtifactStagingDirectory)/Release-API'
       - task: AzureRmWebAppDeployment@4
         inputs:
           ConnectionType: 'AzureRM'
           azureSubscription: '$(ServiceConnectionName)'
           ResourceGroupName: '$(rgname)'
           appType: 'webApp'
           WebAppName: '$(wapp-name)'
           packageForLinux: '$(Build.ArtifactStagingDirectory)/Release-API/drop/*.zip'